In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('phl_hec_all_confirmed.csv')

In [5]:
dataset

,P. Name,P. Name Kepler,P. Name KOI,P. Zone Class,P. Mass Class,P. Composition Class,P. Atmosphere Class,P. Habitable Class,P. Min Mass (EU),P. Mass (EU),...,P. Int ESI,P. Surf ESI,P. ESI,S. HabCat,P. Habitable,P. Hab Moon,P. Confirmed,P. Disc. Method,P. Disc. Year,Unnamed: 68
0,1RXS 1609 b,NaN,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,NaN,4451.16,...,0,0,0.05,0,0,0,1,Imaging,2008,NaN
1,1SWASP J1407 b,NaN,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,6358.80,6358.80,...,0,0,0.07,0,0,0,1,Primary Transit,2012,NaN
2,2M 0103-55(AB) b,NaN,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,4133.22,4133.22,...,0,0,0.06,0,0,0,1,Imaging,2013,NaN
3,2M 0122-24 b,NaN,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,NaN,6358.80,...,0,0,0.08,0,0,0,1,Imaging,2013,NaN
4,2M 0219-39 b,NaN,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,NaN,4419.37,...,0,0,0.06,0,0,0,1,Imaging,2015,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3870,YBP1194 b,NaN,NaN,Hot,Jovian,gas,metals-rich,non-habitable,108.10,108.10,...,0,0,0.16,0,0,0,1,Radial Velocity,2014,NaN
3871,YBP1514 b,NaN,NaN,Hot,Jovian,gas,metals-rich,non-habitable,127.18,127.18,...,0,0,0.15,0,0,0,1,Radial Velocity,2014,NaN
3872,YZ Cet b,NaN,NaN,Hot,Terran,rocky-iron,metals-rich,non-habitable,0.76,0.76,...,0,0,0.43,0,0,0,1,Radial Velocity,2017,NaN
3873,YZ Cet c,NaN,NaN,Hot,Terran,rocky-iron,metals-rich,non-habitable,0.99,0.99,...,0,0,0.53,0,0,0,1,Radial Velocity,2017,NaN
3874,YZ Cet d,NaN,NaN,Hot,Terran,rocky-iron,metals-rich,non-habitable,1.14,1.14,...,0,0,0.65,0,0,0,1,Radial Velocity,2017,NaN

In [13]:
dataset = dataset.drop(['P. Name Kepler','P. Name KOI', 'P. Max Mass (EU)', 'Unnamed: 68', 'P. SPH'],axis = 1)

In [15]:
dataset.fillna(0)

,P. Name,P. Zone Class,P. Mass Class,P. Composition Class,P. Atmosphere Class,P. Habitable Class,P. Min Mass (EU),P. Mass (EU),P. Radius (EU),P. Density (EU),...,P. HZI,P. Int ESI,P. Surf ESI,P. ESI,S. HabCat,P. Habitable,P. Hab Moon,P. Confirmed,P. Disc. Method,P. Disc. Year
0,1RXS 1609 b,Cold,Jovian,gas,hydrogen-rich,non-habitable,0.00,4451.16,19.04,0.64,...,0.00,0,0,0.05,0,0,0,1,Imaging,2008
1,1SWASP J1407 b,Cold,Jovian,gas,hydrogen-rich,non-habitable,6358.80,6358.80,10.94,4.86,...,0.02,0,0,0.07,0,0,0,1,Primary Transit,2012
2,2M 0103-55(AB) b,Cold,Jovian,gas,hydrogen-rich,non-habitable,4133.22,4133.22,11.40,2.79,...,0.00,0,0,0.06,0,0,0,1,Imaging,2013
3,2M 0122-24 b,Cold,Jovian,gas,hydrogen-rich,non-habitable,0.00,6358.80,11.20,4.53,...,0.00,0,0,0.08,0,0,0,1,Imaging,2013
4,2M 0219-39 b,Cold,Jovian,gas,hydrogen-rich,non-habitable,0.00,4419.37,16.13,1.05,...,0.00,0,0,0.06,0,0,0,1,Imaging,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3870,YBP1194 b,Hot,Jovian,gas,metals-rich,non-habitable,108.10,108.10,7.97,0.21,...,0.15,0,0,0.16,0,0,0,1,Radial Velocity,2014
3871,YBP1514 b,Hot,Jovian,gas,metals-rich,non-habitable,127.18,127.18,8.34,0.22,...,0.15,0,0,0.15,0,0,0,1,Radial Velocity,2014
3872,YZ Cet b,Hot,Terran,rocky-iron,metals-rich,non-habitable,0.76,0.76,0.96,0.86,...,0.34,0,0,0.43,0,0,0,1,Radial Velocity,2017
3873,YZ Cet c,Hot,Terran,rocky-iron,metals-rich,non-habitable,0.99,0.99,1.04,0.88,...,0.36,0,0,0.53,0,0,0,1,Radial Velocity,2017
3874,YZ Cet d,Hot,Terran,rocky-iron,metals-rich,non-habitable,1.14,1.14,1.09,0.89,...,0.40,0,0,0.65,0,0,0,1,Radial Velocity,2017

In [16]:
dataset.to_csv('new_data.csv')

In [17]:
dataset.dtypes

P. Name                 object
P. Zone Class           object
P. Mass Class           object
P. Composition Class    object
P. Atmosphere Class     object
                         ...
P. Habitable             int64
P. Hab Moon              int64
P. Confirmed             int64
P. Disc. Method         object
P. Disc. Year           object
Length: 64, dtype: object

In [20]:
obj_df = dataset.select_dtypes(include=['object']).copy()
obj_df

,P. Name,P. Zone Class,P. Mass Class,P. Composition Class,P. Atmosphere Class,P. Habitable Class,P. SFlux Min (EU),P. SFlux Mean (EU),P. SFlux Max (EU),S. Name,S. Name HD,S. Name HIP,S. Constellation,S. Type,P. Disc. Method,P. Disc. Year
0,1RXS 1609 b,Cold,Jovian,gas,hydrogen-rich,non-habitable,4.08E-06,4.08E-06,4.08E-06,1RXS 1609,NaN,NaN,Sco,K7V,Imaging,2008
1,1SWASP J1407 b,Cold,Jovian,gas,hydrogen-rich,non-habitable,0.02166914,0.02166914,0.02166914,1SWASP J1407,NaN,NaN,Cen,K,Primary Transit,2012
2,2M 0103-55(AB) b,Cold,Jovian,gas,hydrogen-rich,non-habitable,3.96E-06,3.96E-06,3.96E-06,2M 0103-55(AB),NaN,NaN,Phe,M,Imaging,2013
3,2M 0122-24 b,Cold,Jovian,gas,hydrogen-rich,non-habitable,1.03E-05,1.03E-05,1.03E-05,2M 0122-24,NaN,NaN,Cet,M3.5,Imaging,2013
4,2M 0219-39 b,Cold,Jovian,gas,hydrogen-rich,non-habitable,2.37E-07,2.37E-07,2.37E-07,2M 0219-39,NaN,NaN,For,M6,Imaging,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3870,YBP1194 b,Hot,Jovian,gas,metals-rich,non-habitable,124.7097,197.4886,331.9188,YBP1194,NaN,NaN,Cnc,G5V,Radial Velocity,2014
3871,YBP1514 b,Hot,Jovian,gas,metals-rich,non-habitable,120.2813,252.3098,624.3745,YBP1514,NaN,NaN,Cnc,G5V,Radial Velocity,2014
3872,YZ Cet b,Hot,Terran,rocky-iron,metals-rich,non-habitable,9.110547,9.110548,9.110549,YZ Cet,NaN,NaN,Cet,M4.5,Radial Velocity,2017
3873,YZ Cet c,Hot,Terran,rocky-iron,metals-rich,non-habitable,4.674975,5.060307,5.48639,YZ Cet,NaN,NaN,Cet,M4.5,Radial Velocity,2017
3874,YZ Cet d,Hot,Terran,rocky-iron,metals-rich,non-habitable,2.268338,2.915344,3.81074,YZ Cet,NaN,NaN,Cet,M4.5,Radial Velocity,2017

In [21]:
obj_df[obj_df.isnull().any(axis=1)]

,P. Name,P. Zone Class,P. Mass Class,P. Composition Class,P. Atmosphere Class,P. Habitable Class,P. SFlux Min (EU),P. SFlux Mean (EU),P. SFlux Max (EU),S. Name,S. Name HD,S. Name HIP,S. Constellation,S. Type,P. Disc. Method,P. Disc. Year
0,1RXS 1609 b,Cold,Jovian,gas,hydrogen-rich,non-habitable,4.08E-06,4.08E-06,4.08E-06,1RXS 1609,NaN,NaN,Sco,K7V,Imaging,2008
1,1SWASP J1407 b,Cold,Jovian,gas,hydrogen-rich,non-habitable,0.02166914,0.02166914,0.02166914,1SWASP J1407,NaN,NaN,Cen,K,Primary Transit,2012
2,2M 0103-55(AB) b,Cold,Jovian,gas,hydrogen-rich,non-habitable,3.96E-06,3.96E-06,3.96E-06,2M 0103-55(AB),NaN,NaN,Phe,M,Imaging,2013
3,2M 0122-24 b,Cold,Jovian,gas,hydrogen-rich,non-habitable,1.03E-05,1.03E-05,1.03E-05,2M 0122-24,NaN,NaN,Cet,M3.5,Imaging,2013
4,2M 0219-39 b,Cold,Jovian,gas,hydrogen-rich,non-habitable,2.37E-07,2.37E-07,2.37E-07,2M 0219-39,NaN,NaN,For,M6,Imaging,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3870,YBP1194 b,Hot,Jovian,gas,metals-rich,non-habitable,124.7097,197.4886,331.9188,YBP1194,NaN,NaN,Cnc,G5V,Radial Velocity,2014
3871,YBP1514 b,Hot,Jovian,gas,metals-rich,non-habitable,120.2813,252.3098,624.3745,YBP1514,NaN,NaN,Cnc,G5V,Radial Velocity,2014
3872,YZ Cet b,Hot,Terran,rocky-iron,metals-rich,non-habitable,9.110547,9.110548,9.110549,YZ Cet,NaN,NaN,Cet,M4.5,Radial Velocity,2017
3873,YZ Cet c,Hot,Terran,rocky-iron,metals-rich,non-habitable,4.674975,5.060307,5.48639,YZ Cet,NaN,NaN,Cet,M4.5,Radial Velocity,2017
3874,YZ Cet d,Hot,Terran,rocky-iron,metals-rich,non-habitable,2.268338,2.915344,3.81074,YZ Cet,NaN,NaN,Cet,M4.5,Radial Velocity,2017

In [26]:
dataset = dataset.dropna(axis=1)
dataset.to_csv('new_data.csv')

In [34]:
obj_df["P. Habitable Class"].value_counts()

non-habitable        3820
mesoplanet             31
psychroplanet          18
hypopsychroplanet       3
thermoplanet            3
Name: P. Habitable Class, dtype: int64

In [36]:
cleanup_nums = {"P. Zone Class":     {"Cold": 1, "Hot": 2, "Warm": 3 },
                "P. Mass Class": {"Jovian": 1, "Superterran": 2, "Neptunian": 3, "Terran": 4,
                                  "Subterran": 5, "Mercurian":6},
               "P. Composition Class": {"gas": 1, "rocky-iron": 2, "rocky-water": 3, "water-gas": 4, "iron": 5},
               "P. Atmosphere Class": {"metals-rich": 1, "hydrogen-rich": 2, "no-atmosphere": 3},
               "P. Habitable Class": {"non-habitable": 1, "mesoplanet": 2, "psychroplanet": 3, "hypopyschroplanet": 4, "thermoplanet": 5}}

In [37]:
obj_df.replace(cleanup_nums, inplace=True)

In [44]:
obj_df = obj_df.drop(['S. Name HD', 'S. Name HIP'], axis = 1)

In [45]:
obj_df.to_csv('new_data.csv')

In [46]:
obj_df

,P. Name,P. Zone Class,P. Mass Class,P. Composition Class,P. Atmosphere Class,P. Habitable Class,P. SFlux Min (EU),P. SFlux Mean (EU),P. SFlux Max (EU),S. Name,S. Constellation,S. Type,P. Disc. Method,P. Disc. Year
0,1RXS 1609 b,1.0,1.0,1.0,2.0,1,4.08E-06,4.08E-06,4.08E-06,1RXS 1609,Sco,K7V,Imaging,2008
1,1SWASP J1407 b,1.0,1.0,1.0,2.0,1,0.02166914,0.02166914,0.02166914,1SWASP J1407,Cen,K,Primary Transit,2012
2,2M 0103-55(AB) b,1.0,1.0,1.0,2.0,1,3.96E-06,3.96E-06,3.96E-06,2M 0103-55(AB),Phe,M,Imaging,2013
3,2M 0122-24 b,1.0,1.0,1.0,2.0,1,1.03E-05,1.03E-05,1.03E-05,2M 0122-24,Cet,M3.5,Imaging,2013
4,2M 0219-39 b,1.0,1.0,1.0,2.0,1,2.37E-07,2.37E-07,2.37E-07,2M 0219-39,For,M6,Imaging,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3870,YBP1194 b,2.0,1.0,1.0,1.0,1,124.7097,197.4886,331.9188,YBP1194,Cnc,G5V,Radial Velocity,2014
3871,YBP1514 b,2.0,1.0,1.0,1.0,1,120.2813,252.3098,624.3745,YBP1514,Cnc,G5V,Radial Velocity,2014
3872,YZ Cet b,2.0,4.0,2.0,1.0,1,9.110547,9.110548,9.110549,YZ Cet,Cet,M4.5,Radial Velocity,2017
3873,YZ Cet c,2.0,4.0,2.0,1.0,1,4.674975,5.060307,5.48639,YZ Cet,Cet,M4.5,Radial Velocity,2017
3874,YZ Cet d,2.0,4.0,2.0,1.0,1,2.268338,2.915344,3.81074,YZ Cet,Cet,M4.5,Radial Velocity,2017